apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-job-worker-deployment
  namespace: mtls-example
  labels:
    app: mtls-job-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-job-worker
  template:
    metadata:
      labels:
        app: mtls-job-worker
    spec:
      containers:
      - name: mtls-job-worker
        image: englaender/mtls-job-worker
